# ------------ AI Models Configuration 3 -------------------------------------------------

# OpenAI Configuration if only it is used

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.openai.com/v1
spring.ai.openai.chat.options.model=gpt-4o-mini-2024-07-18
spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.embedding.options.model=text-embedding-3-small


# Disable Ollama Chat and Embedding autoconfiguration, we will not use Ollama in this configuration
spring.autoconfigure.exclude=\
  org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration,\
  org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration

# ------------ AI Models Configuration 3 -------------------------------------------------