# ------------ AI Models Configuration 1 -------------------------------------------------

# Groq and OpenAI Configuration
# Chat Model: Groq llama-3.3-70b-versatile
# Embedding Model: OpenAI text-embedding-3-small

# Chat Model -> Groq by using OpenAI-compatible API
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
#spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.2

# Embedding -> OpenAI
spring.ai.openai.embedding.base-url=https://api.openai.com/v1
spring.ai.openai.embedding.api-key=${OPENAI_API_KEY}
spring.ai.openai.embedding.options.model=text-embedding-3-small


# Disable Ollama Chat and Embedding autoconfiguration, we will not use Ollama in this configuration
spring.autoconfigure.exclude=\
  org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration,\
  org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration

# ------------ AI Models Configuration 1 -------------------------------------------------