# =================================================================
# Application Identity
# =================================================================
spring.application.name=rag-retriever
spring.profiles.active=groq-chat-openai-embed


# =================================================================
# Server Configuration
# =================================================================
server.port=8082
server.shutdown=graceful
server.servlet.context-path=/rag-retriever


# =================================================================
# Infrastructure (Docker Compose)
# =================================================================
spring.docker.compose.file=./rag-retriever/docker/docker-compose.yaml


# =================================================================
# Observability (OpenTelemetry)
# =================================================================
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces


# =================================================================
# Logging
# =================================================================
logging.level.root=INFO
logging.level.io.jprime.agenticrag.retriever=INFO
logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=DEBUG
logging.level.org.springframework.boot.docker.compose=DEBUG
logging.level.org.springframework.ai=DEBUG