-- V1__create_db_schema.sql
-- Database Schema for Video Production Store

CREATE TABLE VIDEO_EDITING_CARD (
    ID          INT             NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(100)    NOT NULL,
    MANUFACTURER VARCHAR(100)   NOT NULL,
    DESCRIPTION VARCHAR(500)    NOT NULL,
    PRICE       DECIMAL(10, 2)  NOT NULL,
    CONSTRAINT PK_VIDEO_EDITING_CARD PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER (
    ID      INT             NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(100)    NOT NULL,
    EMAIL   VARCHAR(150)    NOT NULL,
    PHONE   VARCHAR(20)     NOT NULL,
    ADDRESS VARCHAR(250)    NOT NULL,
    NOTES   VARCHAR(500),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID),
    CONSTRAINT UQ_CUSTOMER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE STOCK_AVAILABILITY (
    ID                    INT NOT NULL AUTO_INCREMENT,
    VIDEO_EDITING_CARD_ID INT NOT NULL,
    AVAILABILITY          INT NOT NULL,
    CONSTRAINT PK_STOCK_AVAILABILITY PRIMARY KEY (ID),
    CONSTRAINT UQ_STOCK_VIDEO_CARD UNIQUE (VIDEO_EDITING_CARD_ID),
    CONSTRAINT FK_STOCK_VIDEO_CARD FOREIGN KEY (VIDEO_EDITING_CARD_ID)
        REFERENCES VIDEO_EDITING_CARD (ID)
        ON DELETE RESTRICT
);

CREATE TABLE ORDERS (
    ID                    INT          NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID           INT          NOT NULL,
    VIDEO_EDITING_CARD_ID INT          NOT NULL,
    ORDER_DATE            DATE         NOT NULL,
    ORDER_NOTE            VARCHAR(500),
    CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
    CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_ORDERS_VIDEO_CARD FOREIGN KEY (VIDEO_EDITING_CARD_ID)
        REFERENCES VIDEO_EDITING_CARD (ID)
        ON DELETE RESTRICT
);
