# ------------ AI Models Configuration 2 ------------------------------------------------

# Groq and Ollama Configuration
# Chat Model: Groq llama-3.3-70b-versatile
# Embedding Model: Ollama nomic-embed-text

# GROQ Configuration - Chat Model
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.2

# Ollama Configuration - Embedding Model
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.embedding.options.num-batch=2048


# Disable Chat and Embedding autoconfiguration, we will configure them manually in Configuration classes
spring.autoconfigure.exclude=\
  org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration,\
  org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration,\
  org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration

# ------------ AI Models Configuration 2 ------------------------------------------------