# =================================================================
# Application Identity
# =================================================================
spring.application.name=rag-ingestor
spring.profiles.active=groq-chat-openai-embed


# =================================================================
# Server Configuration
# =================================================================
server.port=8081
server.shutdown=graceful
server.servlet.context-path=/rag-ingestor


# =================================================================
# Infrastructure (Docker Compose)
# =================================================================
spring.docker.compose.file=./rag-ingestor/docker/docker-compose.yaml


# =================================================================
# AI Models Configuration
# Active profile determines the model provider.
# Available profiles:
#
# src/main/resources/
#   ├── application.properties
#       ├── application-groq-chat-openai-embed.properties
#       ├── application-groq-chat-ollama-embed.properties
#       ├── application-openai-chat-openai-embed.properties
#       └── application-ollama-chat-ollama-embed.properties
# =================================================================


# =================================================================
# Database Configuration (PostgreSQL)
# =================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/rag_db
spring.datasource.username=rag_user
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5


# =================================================================
# Vector Store Configuration (PgVector)
# =================================================================
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.table-name=vector_store


# =================================================================
# Observability Configuration (OpenTelemetry)
# =================================================================
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces


# =================================================================
# Logging Configuration
# =================================================================
logging.level.root=INFO
logging.level.io.jprime.agenticrag.ingestor=INFO
logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=DEBUG
logging.level.org.springframework.boot.docker.compose=DEBUG
logging.level.org.springframework.ai.vectorstore=DEBUG
logging.level.org.springframework.ai.vectorstore.pgvector=DEBUG
logging.level.org.springframework.ai.ollama=DEBUG
logging.level.org.springframework.ai.ollama.OllamaEmbeddingModel=DEBUG
logging.level.org.springframework.ai.ollama.api.OllamaApi=DEBUG


# =================================================================
# Application Specific Configuration
# =================================================================

# Knowledge Base
app.knowledgebase.path=classpath:knowledge_base/**/*
app.knowledgebase.search.topk=5
app.knowledgebase.search.similarity-threshold=0.4

# ETL Text Splitter
app.etl.textsplitter.chunksize=512
app.etl.textsplitter.minchunksizechars=10
app.etl.textsplitter.minchunklengthtoembed=10
app.etl.textsplitter.maxnumchunks=5000
app.etl.textsplitter.keepseparator=true

