# =================================================================
# Application Identity
# =================================================================
spring.application.name=rag-ingestor


# =================================================================
# Server Configuration
# =================================================================
server.port=8081
server.shutdown=graceful
server.servlet.context-path=/rag-ingestor


# =================================================================
# Infrastructure (Docker Compose)
# =================================================================
spring.docker.compose.file=./rag-ingestor/docker/docker-compose.yaml


# =================================================================
# Observability Configuration (OpenTelemetry)
# =================================================================
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces


# =================================================================
# Logging Configuration
# =================================================================
logging.level.root=INFO
logging.level.io.jprime.agenticrag.ingestor=INFO
logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=DEBUG
logging.level.org.springframework.boot.docker.compose=DEBUG